<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'Nguyễn Hữu Hải',
                'email' => 'hainh@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('HuuHai123@'),
                'phone' => '0976453542',
                'roles_id' => 1,
                'years_of_university' => null,
                'faculty_id' => null,
            ],
            [
                'name' => 'Nguyễn Văn Tùng',
                'email' => 'tungnv@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('VanTung123@'),
                'phone' => '0456235443',
                'roles_id' => 2,
                'years_of_university' => null,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Trần Thị Hương',
                'email' => 'huongtt@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('ThiHuong123@'),
                'phone' => '0945636234',
                'roles_id' => 2,
                'years_of_university' => null,
                'faculty_id' => 2,
            ],

            [
                'name' => 'Lê Văn Đạt',
                'email' => 'datlv@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('VanDat123@'),
                'phone' => '0945633234',
                'roles_id' => 2,
                'years_of_university' => null,
                'faculty_id' => 3,
            ],

            [
                'name' => 'Nguyễn Thị Mỹ Diên',
                'email' => 'dienntm@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('MyDien123@'),
                'phone' => '0945656234',
                'roles_id' => 2,
                'years_of_university' => null,
                'faculty_id' => 4,
            ],

            [
                'name' => 'Nguyễn Thị Yến Linh',
                'email' => 'linhnty@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('YenLinh123@'),
                'phone' => '0945666234',
                'roles_id' => 2,
                'years_of_university' => null,
                'faculty_id' => 5,
            ],
            [
                'name' => 'Giang Minh Tuấn',
                'email' => 'tuangm@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('MinhTuan123@'),
                'phone' => '0759385328',
                'roles_id' => 3,
                'years_of_university' => null,
                'faculty_id' => null,
            ],
            [
                'name' => 'Lê Nguyễn Quốc Khánh',
                'email' => 'khanhlnq@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('QuocKhanh123@'),
                'phone' => '0945834523',
                'roles_id' => 4,
                'years_of_university' => 3,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Nguyễn Vĩnh Phúc',
                'email' => 'phucnv@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('VinhPhuc123@'),
                'phone' => '0674573522',
                'roles_id' => 4,
                'years_of_university' => 3,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Đỗ Thiên Ân',
                'email' => 'andt@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('ThienAn123@'),
                'phone' => '0667453223',
                'roles_id' => 4,
                'years_of_university' => 4,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Phùng Hữu Hoài Tuấn',
                'email' => 'tuanphh@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('HoaiTuan123@'),
                'phone' => '06674532324',
                'roles_id' => 4,
                'years_of_university' => 1,
                'faculty_id' => 2,
            ],
            [
                'name' => 'Nguyễn Thị Ngọc Mai',
                'email' => 'maintn@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('NgocMai123@'),
                'phone' => '0667453236',
                'roles_id' => 4,
                'years_of_university' => 2,
                'faculty_id' => 2,
            ],
            [
                'name' => 'Võ Hoàng Phúc',
                'email' => 'phucvh@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('HoangPhuc123@'),
                'phone' => '0667453223',
                'roles_id' => 4,
                'years_of_university' => 3,
                'faculty_id' => 2,
            ],

            [
                'name' => 'Nguyễn Phú Quý',
                'email' => 'quynp@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('PhuQuy123@'),
                'phone' => '0667453278',
                'roles_id' => 4,
                'years_of_university' => 4,
                'faculty_id' => 3,
            ],
            [
                'name' => 'Nguyễn Trọng Tính',
                'email' => 'tinhnt@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('TrongTinh123@'),
                'phone' => '0667453289',
                'roles_id' => 4,
                'years_of_university' => 1,
                'faculty_id' => 3,
            ],
            [
                'name' => 'Lê Trọng Hiếu',
                'email' => 'hieult@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('TrongHieu123@'),
                'phone' => '0667453853',
                'roles_id' => 4,
                'years_of_university' => 2,
                'faculty_id' => 3,
            ],

            [
                'name' => 'Lê Thanh Nhã',
                'email' => 'nhalt@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('ThanhNha123@'),
                'phone' => '0667459426',
                'roles_id' => 4,
                'years_of_university' => 3,
                'faculty_id' => 4,
            ],
            [
                'name' => 'Nguyễn Thị Như Ý',
                'email' => 'yntn@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('NhuY123@'),
                'phone' => '0667453258',
                'roles_id' => 4,
                'years_of_university' => 4,
                'faculty_id' => 4,
            ],
            [
                'name' => 'Nguyễn Trọng Nghĩa',
                'email' => 'nghiant@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('TrongNghia123@'),
                'phone' => '0667453824',
                'roles_id' => 4,
                'years_of_university' => 1,
                'faculty_id' => 4,
            ],

            [
                'name' => 'Huỳnh Tú Uyên',
                'email' => 'uyenht@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('TuUyen123@'),
                'phone' => '0667453734',
                'roles_id' => 4,
                'years_of_university' => 2,
                'faculty_id' => 5,
            ],
            [
                'name' => 'Lê Trí Thức',
                'email' => 'thuclt@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('TriThuc123@'),
                'phone' => '0667484532',
                'roles_id' => 4,
                'years_of_university' => 3,
                'faculty_id' => 5,
            ],
            [
                'name' => 'Nguyễn Minh Thuận',
                'email' => 'thuannm@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('MinhThuan123@'),
                'phone' => '0667453294',
                'roles_id' => 4,
                'years_of_university' => 4,
                'faculty_id' => 5,
            ],
            [
                'name' => 'Information technology',
                'email' => 'it@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('IT123@'),
                'phone' => null,
                'roles_id' => 5,
                'years_of_university' => null,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Graphic design',
                'email' => 'gd@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('GD123@'),
                'phone' => null,
                'roles_id' => 5,
                'years_of_university' => null,
                'faculty_id' => 2,
            ],
            [
                'name' => 'Business administration',
                'email' => 'ba@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('BA123@'),
                'phone' => null,
                'roles_id' => 5,
                'years_of_university' => null,
                'faculty_id' => 3,
            ],
            [
                'name' => 'Marketing',
                'email' => 'mar@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('Mar123@'),
                'phone' => null,
                'roles_id' => 5,
                'years_of_university' => null,
                'faculty_id' => 4,
            ],
            [
                'name' => 'Artificial intelligence',
                'email' => 'ai@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('AI123@'),
                'phone' => null,
                'roles_id' => 5,
                'years_of_university' => null,
                'faculty_id' => 5,
            ],
            ]);
    }
}
