<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'Nguyễn Hữu Hải',
                'email' => 'hai123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('HuuHai123@'),
                'phone' => '0976453542',
                'roles_id' => 1,
                'years_of_university' => null,
                'faculty_id' => null,
            ],
            [
                'name' => 'Nguyễn Văn Tùng',
                'email' => 'tung123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('Tung123@'),
                'phone' => '0456235443',
                'roles_id' => 2,
                'years_of_university' => null,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Trần Thị Hương',
                'email' => 'huong123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('Huong123@'),
                'phone' => '0945636234',
                'roles_id' => 2,
                'years_of_university' => null,
                'faculty_id' => 2,
            ],

            [
                'name' => 'Lê Văn Đạt',
                'email' => 'dat123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('VanDat123@'),
                'phone' => '0945633234',
                'roles_id' => 2,
                'years_of_university' => null,
                'faculty_id' => 3,
            ],

            [
                'name' => 'Nguyễn Thị Mỹ Diên',
                'email' => 'dien123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('Dien123@'),
                'phone' => '0945656234',
                'roles_id' => 2,
                'years_of_university' => null,
                'faculty_id' => 4,
            ],

            [
                'name' => 'Nguyễn Thị Yến Linh',
                'email' => 'linh123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('Linh123@'),
                'phone' => '0945666234',
                'roles_id' => 2,
                'years_of_university' => null,
                'faculty_id' => 5,
            ],
            [
                'name' => 'Lê Nguyễn Quốc Khánh',
                'email' => 'khanhlnqgcs210497@fpt.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('Khanh123@'),
                'phone' => '0759385328',
                'roles_id' => 3,
                'years_of_university' => null,
                'faculty_id' => null,
            ],
            [
                'name' => 'Giang Minh Tuấn',
                'email' => 'tuan123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('Tuan123@'),
                'phone' => '0945834523',
                'roles_id' => 4,
                'years_of_university' => 3,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Nguyễn Vĩnh Phúc',
                'email' => 'phuc123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('Phuc123@'),
                'phone' => '0674573522',
                'roles_id' => 4,
                'years_of_university' => 3,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Đỗ Thiên Ân',
                'email' => 'an123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('ThienAn123@'),
                'phone' => '0667453223',
                'roles_id' => 4,
                'years_of_university' => 4,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Phùng Hữu Hoài Tuấn',
                'email' => 'tuan123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('Tuan123@'),
                'phone' => '06674532324',
                'roles_id' => 4,
                'years_of_university' => 1,
                'faculty_id' => 2,
            ],
            [
                'name' => 'Nguyễn Thị Ngọc Mai',
                'email' => 'mai123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('NgocMai123@'),
                'phone' => '0667453236',
                'roles_id' => 4,
                'years_of_university' => 2,
                'faculty_id' => 2,
            ],
            [
                'name' => 'Võ Hoàng Phúc',
                'email' => 'phuc123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('Phuc123@'),
                'phone' => '0667453223',
                'roles_id' => 4,
                'years_of_university' => 3,
                'faculty_id' => 2,
            ],

            [
                'name' => 'Nguyễn Phú Quý',
                'email' => 'quy123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('PhuQuy123@'),
                'phone' => '0667453278',
                'roles_id' => 4,
                'years_of_university' => 4,
                'faculty_id' => 3,
            ],
            [
                'name' => 'Nguyễn Trọng Tính',
                'email' => 'tinh123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('Tinh123@'),
                'phone' => '0667453289',
                'roles_id' => 4,
                'years_of_university' => 1,
                'faculty_id' => 3,
            ],
            [
                'name' => 'Lê Trọng Hiếu',
                'email' => 'hieu123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('Hieu123@'),
                'phone' => '0667453853',
                'roles_id' => 4,
                'years_of_university' => 2,
                'faculty_id' => 3,
            ],

            [
                'name' => 'Lê Thanh Nhã',
                'email' => 'nha123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('ThanhNha123@'),
                'phone' => '0667459426',
                'roles_id' => 4,
                'years_of_university' => 3,
                'faculty_id' => 4,
            ],
            [
                'name' => 'Nguyễn Thị Như Ý',
                'email' => 'nhuy123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('NhuY123@'),
                'phone' => '0667453258',
                'roles_id' => 4,
                'years_of_university' => 4,
                'faculty_id' => 4,
            ],
            [
                'name' => 'Nguyễn Trọng Nghĩa',
                'email' => 'nghia123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('Nghia123@'),
                'phone' => '0667453824',
                'roles_id' => 4,
                'years_of_university' => 1,
                'faculty_id' => 4,
            ],

            [
                'name' => 'Huỳnh Tú Uyên',
                'email' => 'uyen123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('Uyen123@'),
                'phone' => '0667453734',
                'roles_id' => 4,
                'years_of_university' => 2,
                'faculty_id' => 5,
            ],
            [
                'name' => 'Lê Trí Thức',
                'email' => 'thuc123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('Thuc123@'),
                'phone' => '0667484532',
                'roles_id' => 4,
                'years_of_university' => 3,
                'faculty_id' => 5,
            ],
            [
                'name' => 'Nguyễn Minh Thuận',
                'email' => 'thuan123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('Thuan123@'),
                'phone' => '0667453294',
                'roles_id' => 4,
                'years_of_university' => 4,
                'faculty_id' => 5,
            ],
            [
                'name' => 'Information technology',
                'email' => 'it@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('IT123@'),
                'phone' => null,
                'roles_id' => 5,
                'years_of_university' => null,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Graphic design',
                'email' => 'gd@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('GD123@'),
                'phone' => null,
                'roles_id' => 5,
                'years_of_university' => null,
                'faculty_id' => 2,
            ],
            [
                'name' => 'Business administration',
                'email' => 'ba@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('BA123@'),
                'phone' => null,
                'roles_id' => 5,
                'years_of_university' => null,
                'faculty_id' => 3,
            ],
            [
                'name' => 'Marketing',
                'email' => 'mar@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('Mar123@'),
                'phone' => null,
                'roles_id' => 5,
                'years_of_university' => null,
                'faculty_id' => 4,
            ],
            [
                'name' => 'Artificial intelligence',
                'email' => 'ai@fe.edu.vn',
                'email_verified_at' => now(),
                'password' => Hash::make('AI123@'),
                'phone' => null,
                'roles_id' => 5,
                'years_of_university' => null,
                'faculty_id' => 5,
            ],
            ]);
    }
}
